/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package TodoApp.view;

import TodoApp.controller.TaskController;
import TodoApp.model.Project;
import TodoApp.model.Task;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author marco
 */
public class TaskDialogScreen extends javax.swing.JDialog {

    /**
     * Creates new form ProjectDialogScreen
     */
    TaskController taskController;
    Project project;

    public JTextArea getTasksContentNotesJTextArea() {
        return tasksContentNotesJTextArea;
    }

    public JTextArea getTasksContentDescriptionjTextArea() {
        return tasksContentDescriptionjTextArea;
    }

    public JFormattedTextField getTasksContentDeadlinejFormattedTextField1() {
        return tasksContentDeadlinejFormattedTextField1;
    }

    public JTextField getTasksContentNameJTextField() {
        return tasksContentNameJTextField;
    }
 
    
    public TaskDialogScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        taskController = new TaskController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tasksHeaderJPanel = new javax.swing.JPanel();
        tasksHeaderTitleJLabel = new javax.swing.JLabel();
        tasksHeaderIconJLabel = new javax.swing.JLabel();
        tasksContentJPanel = new javax.swing.JPanel();
        tasksContentNameJPanel = new javax.swing.JLabel();
        tasksContentNameJTextField = new javax.swing.JTextField();
        tasksContentDescriptionJLabel = new javax.swing.JLabel();
        tasksContentjScrollPane = new javax.swing.JScrollPane();
        tasksContentDescriptionjTextArea = new javax.swing.JTextArea();
        tasksContentDeadlineJPanel = new javax.swing.JLabel();
        tasksContentNotesJPanel = new javax.swing.JLabel();
        tasksContentjScrollPane2 = new javax.swing.JScrollPane();
        tasksContentNotesJTextArea = new javax.swing.JTextArea();
        tasksContentDeadlinejFormattedTextField1 = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(229, 229, 229));

        tasksHeaderJPanel.setBackground(new java.awt.Color(139, 45, 186));

        tasksHeaderTitleJLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tasksHeaderTitleJLabel.setForeground(java.awt.Color.white);
        tasksHeaderTitleJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tasksHeaderTitleJLabel.setText("Task");

        tasksHeaderIconJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check.png"))); // NOI18N
        tasksHeaderIconJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tasksHeaderIconJLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tasksHeaderJPanelLayout = new javax.swing.GroupLayout(tasksHeaderJPanel);
        tasksHeaderJPanel.setLayout(tasksHeaderJPanelLayout);
        tasksHeaderJPanelLayout.setHorizontalGroup(
            tasksHeaderJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tasksHeaderJPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(tasksHeaderTitleJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                .addComponent(tasksHeaderIconJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        tasksHeaderJPanelLayout.setVerticalGroup(
            tasksHeaderJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tasksHeaderJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tasksHeaderJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tasksHeaderTitleJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tasksHeaderIconJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addContainerGap())
        );

        tasksContentJPanel.setBackground(java.awt.Color.white);

        tasksContentNameJPanel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tasksContentNameJPanel.setText("Name");

        tasksContentNameJTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tasksContentNameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tasksContentNameJTextFieldActionPerformed(evt);
            }
        });

        tasksContentDescriptionJLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tasksContentDescriptionJLabel.setText("Description");

        tasksContentDescriptionjTextArea.setColumns(20);
        tasksContentDescriptionjTextArea.setRows(5);
        tasksContentjScrollPane.setViewportView(tasksContentDescriptionjTextArea);

        tasksContentDeadlineJPanel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tasksContentDeadlineJPanel.setText("Deadline");

        tasksContentNotesJPanel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tasksContentNotesJPanel.setText("Notes");

        tasksContentNotesJTextArea.setColumns(20);
        tasksContentNotesJTextArea.setRows(5);
        tasksContentjScrollPane2.setViewportView(tasksContentNotesJTextArea);

        tasksContentDeadlinejFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        tasksContentDeadlinejFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tasksContentDeadlinejFormattedTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tasksContentJPanelLayout = new javax.swing.GroupLayout(tasksContentJPanel);
        tasksContentJPanel.setLayout(tasksContentJPanelLayout);
        tasksContentJPanelLayout.setHorizontalGroup(
            tasksContentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tasksContentJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tasksContentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tasksContentjScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tasksContentNameJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tasksContentNameJTextField)
                    .addComponent(tasksContentDescriptionJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                    .addComponent(tasksContentjScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tasksContentNotesJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                    .addComponent(tasksContentDeadlineJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tasksContentDeadlinejFormattedTextField1))
                .addContainerGap())
        );
        tasksContentJPanelLayout.setVerticalGroup(
            tasksContentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tasksContentJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tasksContentNameJPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tasksContentNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tasksContentDescriptionJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tasksContentjScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tasksContentDeadlineJPanel)
                .addGap(4, 4, 4)
                .addComponent(tasksContentDeadlinejFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tasksContentNotesJPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tasksContentjScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tasksContentJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tasksHeaderJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tasksHeaderJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tasksContentJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tasksContentNameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tasksContentNameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tasksContentNameJTextFieldActionPerformed

    private void tasksContentDeadlinejFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tasksContentDeadlinejFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tasksContentDeadlinejFormattedTextField1ActionPerformed

    private void tasksHeaderIconJLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tasksHeaderIconJLabelMouseClicked
        try {
            Task task = new Task();

            task.setIdProject(project.getId());
            String text = tasksContentNameJTextField.getText();
            //faço isso pois o nome não pois de acordo com a regra de negócio que eu defini no My Sql
            //o nome não pode ser null e quando eu não digito nada ele manda uma string vazia.
            // por isso que eu transformo em null caso seja vazia
            task.setName(!text.equals("") ? text : null); 
            task.setDescription(tasksContentDescriptionjTextArea.getText());
            task.setCompleted(false);
            text = tasksContentDeadlinejFormattedTextField1.getText();

            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            task.setDeadLine(!text.replace("/", "").equals("") ? dateFormat.parse(text) : null);

            task.setNotes(tasksContentNotesJTextArea.getText());
            taskController.save(task);
            JOptionPane.showMessageDialog(rootPane, "The task was succesfully created");
            this.dispose();
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
        
    }//GEN-LAST:event_tasksHeaderIconJLabelMouseClicked
    
      public void setProject(Project project) {
        this.project = project;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TaskDialogScreen dialog = new TaskDialogScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel tasksContentDeadlineJPanel;
    private javax.swing.JFormattedTextField tasksContentDeadlinejFormattedTextField1;
    private javax.swing.JLabel tasksContentDescriptionJLabel;
    private javax.swing.JTextArea tasksContentDescriptionjTextArea;
    private javax.swing.JPanel tasksContentJPanel;
    private javax.swing.JLabel tasksContentNameJPanel;
    private javax.swing.JTextField tasksContentNameJTextField;
    private javax.swing.JLabel tasksContentNotesJPanel;
    private javax.swing.JTextArea tasksContentNotesJTextArea;
    private javax.swing.JScrollPane tasksContentjScrollPane;
    private javax.swing.JScrollPane tasksContentjScrollPane2;
    private javax.swing.JLabel tasksHeaderIconJLabel;
    private javax.swing.JPanel tasksHeaderJPanel;
    private javax.swing.JLabel tasksHeaderTitleJLabel;
    // End of variables declaration//GEN-END:variables
}
